name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pest:
    name: PHP ${{ matrix.php }} • Pest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["8.2", "8.3", "8.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, tokenizer
          coverage: ${{ matrix.php == '8.4' && 'xdebug' || 'none' }}
          tools: composer:v2

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run tests (no coverage)
        if: matrix.php != '8.4'
        run: vendor/bin/pest --ci

      - name: Run tests with coverage (Xdebug)
        if: matrix.php == '8.4'
        run: |
          mkdir -p build/logs
          XDEBUG_MODE=coverage vendor/bin/pest --ci --coverage-clover build/logs/clover.xml

      - name: Upload coverage artifact
        if: matrix.php == '8.4'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-clover
          path: build/logs/clover.xml
